const dummyData = [
  {
    id: '1',
    name: 'Sebastian Rudiger',
    message: 'Perfect! Will check it 🔥',
    time: '09:34 PM',
    unreadCount: 0,
    image: 'https://randomuser.me/api/portraits/men/32.jpg',
  },
  {
    id: '2',
    name: 'Caroline Varsaha',
    message: 'Thanks, Jimmy! Talk later',
    time: '08:12 PM',
    unreadCount: 2,
    image: 'https://randomuser.me/api/portraits/women/44.jpg',
  },
  {
    id: '3',
    name: 'Darshan Patelchi',
    message: 'Sound good for me too!',
    time: '02:29 PM',
    unreadCount: 3,
    image: 'https://randomuser.me/api/portraits/men/78.jpg',
  },
  {
    id: '4',
    name: 'Mohammed Arnold',
    message: 'No rush, mate! Just let ...',
    time: '01:08 PM',
    unreadCount: 0,
    image: 'https://randomuser.me/api/portraits/men/41.jpg',
  },
  {
    id: '5',
    name: 'Tamara Schipchinskaya',
    message: "Okay. I'll tell him about it",
    time: '11:15 AM',
    unreadCount: 0,
    image: 'https://randomuser.me/api/portraits/women/25.jpg',
  },
  {
    id: '6',
    name: 'Ariana Amberline',
    message: 'Good nite, Honey! 🖤',
    time: 'Yesterday',
    unreadCount: 0,
    image: 'https://randomuser.me/api/portraits/women/68.jpg',
  },
];
